import { Content } from './content';
import { Network } from '../shared';
import { TContentPlugin } from '@ts-libs/ui-base';
import { Ti18nPlugin } from '@ts-libs/ui-i18n';

export const NetworkInterfaces: TContentPlugin & Ti18nPlugin = {
  name: 'netifs',
  use: Network,
  content: {
    title: 'Interfaces',
    component: Content,
    menu: { parent: Network.name },
  },
  i18n: {
    resources: {
      de: {
        initial: 'initial',
        started: 'gestartet',
        stopped: 'gestoppt',
        Default: 'Standard',
        'Static IP': 'Statische IP',
        'DHCP client': 'DHCP-Client',
        'DHCP server': 'DHCP-Server',
        'IP address': 'IP Adresse',
        Netmask: 'Netzmaske',
        Gateway: 'Gateway',
        'Primary DNS': 'Primärer DNS',
        'Secondary DNS': 'Sekundärer DNS',
        'Fallback DNS': 'Fallback-DNS',
        'MAC address': 'MAC-Adresse',
        'IP gateway': 'IP-Gateway',
        'IPv6 address': 'IPv6-Adresse',
        'DNS servers': 'DNS-Server',
        Priority: 'Priorität',
        up: 'eingeschaltet',
        down: 'heruntergefahren',
        'Configure interface': 'Netzwerkschnittstelle konfigurieren',
        'Interface role': 'Schnittstellenrolle',
        Interfaces: 'Schnittstellen',
      },
      uk: {
        initial: 'початковий',
        started: 'працює',
        stopped: 'зупинений',
        Default: 'За замовчанням',
        'Static IP': 'Статичний IP',
        'DHCP client': 'DHCP клієнт',
        'DHCP server': 'DHCP сервер',
        'IP address': 'IP адреса',
        Netmask: 'Маска мережі',
        Gateway: 'Шлюз',
        'Primary DNS': 'Головний DNS',
        'Secondary DNS': 'Другорядний DNS',
        'Fallback DNS': 'Аварійний DNS',
        'MAC address': 'MAC адреса',
        'IP gateway': 'IP шлюз',
        'IPv6 address': 'IPv6 адреса',
        'DNS servers': 'DNS сервер',
        Priority: 'Приорітет',
        up: 'працює',
        down: 'зупинений',
        'Configure interface': 'Конфігурація інтерфейсу',
        'Interface role': 'Роль інтерфейсу',
        Interfaces: 'Інтерфейси',
      },
      it: {
        initial: 'iniziale',
        started: 'avviato',
        stopped: 'fermato',
        Default: 'Predefinito',
        'Static IP': 'IP statico',
        'DHCP client': 'DHCP client',
        'DHCP server': 'DHCP server',
        'IP address': 'Indirizzo IP',
        Netmask: 'Maschera di rete',
        Gateway: 'Gateway',
        'Primary DNS': 'DNS primario',
        'Secondary DNS': 'DNS secondario',
        'Fallback DNS': 'DNS di fallback',
        'MAC address': 'Indirizzo MAC',
        'IP gateway': 'IP gateway',
        'IPv6 address': 'Indirizzo IPv6',
        'DNS servers': 'Server DNS',
        Priority: 'Priorità',
        up: 'avviato',
        down: 'fermato',
        'Configure interface': 'Configura interfaccia',
        'Interface role': 'Ruolo interfaccia',
        Interfaces: 'Interfacce',
      },
    },
  },
};
